using MongoDB.Driver;
using CoachingService.Models;
using System;

public class CoachingRepository : ICoachingRepository
{
    private readonly IMongoCollection<Session> _sessionsCollection;

    public CoachingRepository(IMongoDatabase database)
    {
       
        _sessionsCollection = database.GetCollection<Session>("Sessions"); 
    }

    public Session BookSession(Session session)
    {
        if (session == null)
            throw new ArgumentNullException(nameof(session));

        // Enforce simple invariants and business logic:
        if (session.EndTime <= session.StartTime)
            throw new ArgumentException("EndTime must be after StartTime");

        // Set invariants that the Controller might not set
        if (session.BookingForm != null && session.BookingForm.CreatedAt == default)
            session.BookingForm.CreatedAt = DateTime.UtcNow;

        if (session.CurrentStatus == default)
            session.CurrentStatus = Session.Status.Planned;

        // Synchronous MongoDB Insert
        _sessionsCollection.InsertOne(session);

        // The session object now has the Id generated by MongoDB
        return session;
    }
    
    public IEnumerable<Session> GetAllSessions()
    {
        return _sessionsCollection.Find(FilterDefinition<Session>.Empty).ToList();
    }
}